version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:20"
      timezone: "America/Chicago"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:20"
      timezone: "America/Chicago"